### ISSUE TITLE
Command center page throws an error when you open Configuration/Overview in Command center

### ISSUE THREAD

**Issue by nemigaservices** [kaazing/gateway#320]
Download AMQP Gateway from Kaazing.com (4.0.6.57)
Start the gateway and the server.
Login as admin/admin.
Go to configuration/overview.

Javascript error appears:

Error message: Uncaught TypeError: Cannot read property 'cssServiceType' of undefined
URL: http://localhost:8000/commandcenter/js/views.js
Line Number: 2797

**Comment by mgherghe** [comment]
@sbadugu This issue also occurs in gateway EE when the 'amqp' service is configured. This is due to the fact that in the [constants.js](https://github.com/kaazing/kaazing-command-center/blob/develop/src/js/constants.js) file there is no constant for the amqp.proxy service (there is also no image for this service in the `web\commandcenter\images` folder). 
I attached a [screenshot](https://cloud.githubusercontent.com/assets/11552767/13957213/5c89c76c-f054-11e5-95dd-47ea77e7f10f.png) with this alert error.

**Comment by sbadugu** [comment]
Command center is going to be deprecated. This won't be fixed.
