### ISSUE TITLE
RFC 7232: Directory Service responds with 200 OK when If-Modified-Since matches Last-Modified from previous response

### ISSUE THREAD

**Issue by cmebarrow** [kaazing/gateway#383]
Test case is IfModifiedSinceIT in module service/http.directory. The two test methods that fail because of this bug are shouldResultInNotModifiedResponseWithGetAndConditionFailed and shouldResultInNotModifiedResponseWithHeadAndConditionFailed

**Comment by DoruM** [comment]
Hello Chris,

I have reproduced this issue. We are sending precision in seconds on the "Last-Modified" header, but we are checking with millisecond precision on "If-Modified-Since". 

A header with sub-second precision is non-HTTP compliant, according to [RFC822](https://www.w3.org/Protocols/rfc822/#z28). 

Best regards, 
Doru


----------------------
##### Longer technical details
 The problem is that at [this line](https://github.com/kaazing/gateway/blob/develop/transport/http/src/main/java/org/kaazing/gateway/transport/http/HttpUtils.java#L291) the code formats the header Last-Modified as ""EEE, dd MMM yyyy HH:mm:ss zzz" (defined [here](https://github.com/kaazing/gateway/blob/develop/transport/http/src/main/java/org/kaazing/gateway/transport/http/HttpUtils.java#L87)). 

This causes a problem because this format is accurate to the second. On the other hand, when checking for the "If-Modified-Since" we are accurate to the millisecond (because we use the java.io.File.lastModified).

-------------------
##### Subsecond accuracy
I believe that for directory service, sub-second accuracy is not important, that is why I will create a pull request for this bug rounding to the nearest second.  If on the other hand we do need sub-second accuracy, I believe entity tags should be used and I will need a bit more input if you need this

@cmebarrow

**Comment by DoruM** [comment]
This issue is solved in this [PR](https://github.com/kaazing/gateway/pull/633)

**Comment by cmebarrow** [comment]
@DoruM Thanks, your analysis sounds reasonable. Please assign the PR to someone else to review since I am too busy (see my comment in the PR)
