### ISSUE TITLE
Errors in HTTP Requests

### ISSUE THREAD

**Issue by a-zuckut** [kaazing/gateway#636]
Errors in rfc7230: MessageFormatIT
- inboundShouldRejectInvalidRequestLine
- serverShouldSend414ToRequestWithTooLongARequest
- serverShouldRejectOBSInHeaderValue
- proxyOrGatewayMustRejectOBSInHeaderValue
- robustServerShouldAllowExtraCRLFAfterRequestLine
- inboundMustRejectRequestWithUserInfoOnURI

**Comment by StCostea** [comment]
I have checked all the tests under gateway/specification/http. In Windows there are 4 tests that are failing (only one from this class), but under Ubuntu there is none. I suspect the same problem I had few days ago with the firewall/antivirus on windows.

So there is nothing to fix here. If you want, I can take a look at the failed tests under Windows to confirm if it is because of firewall/antivirus or some other kind of error. Do you want me to check it ?
