### ISSUE TITLE
Unknown Transfer Encoding Header Test failure

### ISSUE THREAD

**Issue by a-zuckut** [kaazing/gateway#638]
@dpwspoon Here is the bug/implementation that you and John were discussing regarding specification test: `serverShouldSend501ToUnknownTransferEncoding`.

**Comment by dpwspoon** [comment]
Looking at this test, we don't return the correct error code when we detect unknown transfer encodings.  I would suggest we add supported transfer encodings as a ResourceOption to the http layer with reasonable defaults and return it.

**Comment by dpwspoon** [comment]
Links to related tests: https://github.com/kaazing/gateway/pull/644

**Comment by dpwspoon** [comment]
Note: http proxy should allow * and forward blindly

**Comment by dpwspoon** [comment]
> Moreover, it is unclear to me what the proper behavior is in the http.proxy, where we probably should not be looking at the transfer-encoding, and instead we should consider just blindly forwarding it. To support this second use case maybe we could add a new HttpResourceOption with reasonable defaults and return it. When http proxy is configured the resource option could be * and it should accept all.

After talking to Jitu we should just support the RFC transfer-encodings, so no need for http proxy resource address

**Comment by vmaraloiu** [comment]
This fix implies also to remove the [line](https://github.com/kaazing/gateway/blob/develop/transport/http/src/main/java/org/kaazing/gateway/transport/http/bridge/filter/HttpRequestDecodingState.java#L250), because for header `write header "Transfer-Encoding" "Unknown"` the gateway throws an exception and the test fails. There seems not to be tests from `gateway.transport.http` covering the removed line.
Created this [PR](https://github.com/kaazing/gateway/pull/859).

**Comment by vmaraloiu** [comment]
@sbadugu The PR is merged. This bug can be closed.
