### ISSUE TITLE
Can't specify size units for <maximum.pending.bytes> in configuration

### ISSUE THREAD

**Issue by robinzimmermann** [kaazing/gateway#673]
The following property causes the gateway to give an error on startup and fail to start:

``` xml
  <service>
    <name>Proxy Service</name>
    <accept>...</accept>
    <connect>...</connect>

    <type>proxy</type>

    <properties>
      <maximum.pending.bytes>128kB</maximum.pending.bytes>
    </properties>

  </service>
```

The [doc](http://kaazing.com/doc/5.0/admin-reference/r_configure_gateway_service/index.html#proxy-amqpproxy-and-jmsproxy) says this should work (search for `maximum.pending.bytes`):

> The value must be a positive integer with either no specified unit or appended with kB or MB (the unit is case insensitive) to indicate kilobytes or megabytes.

All variations with `kb` fail. e.g. `128 kB`, 128KB`, etc.

Workaround is to specify `128000`.

**Comment by mgherghe** [comment]
@robinzimmermann @sbadugu In the xsd file, the `maximum.pending.bytes` property is declared with the same type as the `ws.maximum.message.size` property, which accepts values of positive integers, followed by a k, K, m, or M, as specified in the [doc](https://kaazing.com/doc/5.0/admin-reference/r_configure_gateway_service/index.html#wsmaximummessagesize
ws.maximum.message.size).

This can be fixed with one of the following:
- changing the documentation for the `maximum.pending.bytes` property to match the xsd definition (append k or m to the integer value, instead of kB or MB)
- changing both properties to accept kB or MB, which would also imply updating the documentation for the `ws.maximum.message.size` property

**Comment by sbadugu** [comment]
Thanks @mgherghe !

I like your first proposal, we should be consistent with our property values and it's better to change the documentation for `maximum.pending.bytes` in order to match with the documentation of `ws.maximum.message.size`.

**Comment by sbadugu** [comment]
@michaelcretzman 
Can we replicate the following description used in the doc for `ws.maximum.message.size` property and reuse it for `maximum.pending.bytes` as well ?

```
If you specify ws.maximum.message.size in the gateway-config.xml file, then specify a positive integer. You can append a k, K, m, or M to indicate kilobytes or megabytes (the unit is case insensitive). If a unit is not included, then ws.maximum.message.size defaults to bytes. For example:

A value of 2048 sets the buffer to 2048 bytes
A value of 128K sets the buffer to 128 kilobytes
A value of 128M sets the buffer to 128 megabytes
```

**Comment by ghost** [comment]
@robinzimmermann this is fixed:

https://kaazing.com/doc/5.0/admin-reference/r_configure_gateway_service/index.html#section

The value format for `maximum.pending.bytes` is now the same as `ws.maximum.message.size` in the docs.
